// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./components/ActionCard/ActionCard.vue')['default']
    AppBar: typeof import('./components/AppBar/AppBar.vue')['default']
    Avatar: typeof import('./modules/vuwi/src/components/Avatar/Avatar.vue')['default']
    Background: typeof import('./components/Background/Background.vue')['default']
    Calendar: typeof import('./modules/vuwi/src/components/DatePicker/components/Calendar.vue')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CodeInput: typeof import('./modules/vuwi/src/components/CodeInput/CodeInput.vue')['default']
    Collapse: typeof import('./modules/vuwi/src/components/Collapse/Collapse.vue')['default']
    DatePicker: typeof import('./modules/vuwi/src/components/DatePicker/DatePicker.vue')['default']
    Dialog: typeof import('./modules/vuwi/src/components/Dialog/Dialog.vue')['default']
    Drawer: typeof import('./modules/vuwi/src/components/Drawer/Drawer.vue')['default']
    Dropdown: typeof import('./modules/vuwi/src/components/Dropdown/Dropdown.vue')['default']
    Dropzone: typeof import('./modules/vuwi/src/components/Dropzone/Dropzone.vue')['default']
    FilePreview: typeof import('./modules/vuwi/src/components/FilePreview/FilePreview.vue')['default']
    FileSelector: typeof import('./modules/vuwi/src/components/FileSelector/FileSelector.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    FormSection: typeof import('./modules/vuwi/src/components/FormSection/FormSection.vue')['default']
    Header: typeof import('./modules/vuwi/src/components/DatePicker/components/Header.vue')['default']
    Line: typeof import('./modules/vuwi/src/components/Line/Line.vue')['default']
    Month: typeof import('./modules/vuwi/src/components/DatePicker/components/Month.vue')['default']
    Navigation: typeof import('./components/Navigation/Navigation.vue')['default']
    Overlay: typeof import('./modules/vuwi/src/components/Overlay/Overlay.vue')['default']
    Pagination: typeof import('./modules/vuwi/src/components/Pagination/Pagination.vue')['default']
    README: typeof import('./components/README.md')['default']
    Select: typeof import('./modules/vuwi/src/components/Select/Select.vue')['default']
    Shortcut: typeof import('./modules/vuwi/src/components/DatePicker/components/Shortcut.vue')['default']
    Switch: typeof import('./modules/vuwi/src/components/Switch/Switch.vue')['default']
    TablerBox: typeof import('~icons/tabler/box')['default']
    TablerChevronUp: typeof import('~icons/tabler/chevron-up')['default']
    TablerLogout: typeof import('~icons/tabler/logout')['default']
    TablerMenu2: typeof import('~icons/tabler/menu2')['default']
    TablerMessage: typeof import('~icons/tabler/message')['default']
    TablerUser: typeof import('~icons/tabler/user')['default']
    Textarea: typeof import('./modules/vuwi/src/components/Textarea/Textarea.vue')['default']
    Textfield: typeof import('./modules/vuwi/src/components/Textfield/Textfield.vue')['default']
    Toast: typeof import('./modules/vuwi/src/components/Toast/Toast.vue')['default']
    ToggleDarkMode: typeof import('./components/ToggleDarkMode/ToggleDarkMode.vue')['default']
    ToggleVisible: typeof import('./components/ToggleVisible/ToggleVisible.vue')['default']
    Tooltip: typeof import('./modules/vuwi/src/components/Tooltip/Tooltip.vue')['default']
    Week: typeof import('./modules/vuwi/src/components/DatePicker/components/Week.vue')['default']
    Year: typeof import('./modules/vuwi/src/components/DatePicker/components/Year.vue')['default']
  }
}

export { }
